services:
  unsloth:
    image: schlammsuhler/unsloth:2.7.0-cuda12.6-flash-attn
    container_name: unsloth
    build:
      context: .
      dockerfile: docker/unsloth-pytorch.dockerfile
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - HF_HOME=/workspace/hf-cache
    volumes:
      - hf-cache:/workspace/hf-cache
      - "D:/ai/outputs:/workspace/outputs"
      - ./recipes:/workspace/recipes
      - ./datasets:/workspace/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #command: ["bash"]
    tty: true
    stdin_open: true
    env_file: ".env"

  # jupyter:
  #   image: jupyter
  #   build:
  #     context: .
  #     dockerfile: docker/jupyter.dockerfile
  #   environment:
  #     - WANDB_API_KEY=${WANDB_API_KEY}
  #     - HF_TOKEN=${HF_TOKEN}
  #     - HF_HUB_ENABLE_HF_TRANSFER=1
  #     - HF_HOME=/workspace/hf-cache

volumes:
  hf-cache:
    name: "hf-cache"
    external: true
