services:
  unsloth:
    image: unsloth
    build: .
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - HF_HOME=/workspace/hf-cache
    volumes:
      - hub:/workspace/hf-cache
      - "D:/ai/unsloth:/workspace/outputs"
      - ./recipes:/workspace/recipes
      - ./datasets:/workspace/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash"]
    tty: true
    stdin_open: true

volumes:
  hub:
    driver: local
    name: "huggingface-cache"
  outputs:
    driver: local
